redirectsOrigin = "config"
plugins = []
headers = []

[functions]

  [functions."*"]

[build]
publish = "C:\\Users\\danielrosh\\Desktop\\bug1\\idan\\final1"
publishOrigin = "config"

  [build.environment]

  [build.processing]

    [build.processing.css]

    [build.processing.html]

    [build.processing.images]

    [build.processing.js]

  [build.services]

[[redirects]]
from = "/order.html"
to = "/order"
status = 301
force = false

  [redirects.query]

  [redirects.conditions]

  [redirects.headers]

[[redirects]]
from = "/buy"
to = "/order"
status = 301
force = false

  [redirects.query]

  [redirects.conditions]

  [redirects.headers]

[[redirects]]
from = "/checkout"
to = "/order"
status = 301
force = false

  [redirects.query]

  [redirects.conditions]

  [redirects.headers]

[[redirects]]
from = "/shop/order"
to = "/order"
status = 301
force = false

  [redirects.query]

  [redirects.conditions]

  [redirects.headers]

[[redirects]]
from = "/purchase"
to = "/order"
status = 301
force = false

  [redirects.query]

  [redirects.conditions]

  [redirects.headers]

[[redirects]]
from = "/order/*"
to = "/order.html"
status = 200
force = false

  [redirects.query]

  [redirects.conditions]

  [redirects.headers]

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
force = false

  [redirects.query]

  [redirects.conditions]

  [redirects.headers]